//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Shop
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Position list.
    /// </summary>
    // *** Start programmer edit section *** (PositionList CustomAttributes)

    // *** End programmer edit section *** (PositionList CustomAttributes)
    public enum PositionList
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (PositionList.StoreKeeper CustomAttributes)

        // *** End programmer edit section *** (PositionList.StoreKeeper CustomAttributes)
        StoreKeeper,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (PositionList.Manager CustomAttributes)

        // *** End programmer edit section *** (PositionList.Manager CustomAttributes)
        Manager,
    }
}
