//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Shop
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Invoice status.
    /// </summary>
    // *** Start programmer edit section *** (InvoiceStatus CustomAttributes)

    // *** End programmer edit section *** (InvoiceStatus CustomAttributes)
    public enum InvoiceStatus
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (InvoiceStatus.New CustomAttributes)

        // *** End programmer edit section *** (InvoiceStatus.New CustomAttributes)
        New,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (InvoiceStatus.Issued CustomAttributes)

        // *** End programmer edit section *** (InvoiceStatus.Issued CustomAttributes)
        Issued,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (InvoiceStatus.Paused CustomAttributes)

        // *** End programmer edit section *** (InvoiceStatus.Paused CustomAttributes)
        Paused,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (InvoiceStatus.Ready CustomAttributes)

        // *** End programmer edit section *** (InvoiceStatus.Ready CustomAttributes)
        Ready,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (InvoiceStatus.Shipped CustomAttributes)

        // *** End programmer edit section *** (InvoiceStatus.Shipped CustomAttributes)
        Shipped,
    }
}
