//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Shop
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Order status.
    /// </summary>
    // *** Start programmer edit section *** (OrderStatus CustomAttributes)

    // *** End programmer edit section *** (OrderStatus CustomAttributes)
    public enum OrderStatus
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (OrderStatus.New CustomAttributes)

        // *** End programmer edit section *** (OrderStatus.New CustomAttributes)
        New,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (OrderStatus.Paid CustomAttributes)

        // *** End programmer edit section *** (OrderStatus.Paid CustomAttributes)
        Paid,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (OrderStatus.Canceled CustomAttributes)

        // *** End programmer edit section *** (OrderStatus.Canceled CustomAttributes)
        Canceled,
    }
}
